# WhitelistedAdmin configuration


# Placeholder list:
#   {player}: Player name
#   {address}: Player IP Address in PlayerJoinEvent
#   {current_address}: Player IP Address in the configuration


# List of permissions to check
# Wildcard (e.g. "bukkit.*") are supported, it will check if the player have any permission starting with "bukkit.", for example.
permissions:
  - "bukkit.plugin"
  - "bukkit.?"
  - "idk"

# List of whitelisted administrator and their IP address
whitelisted:
  remember-to-replace-this-to-your-admin-name: "127.0.0.1"
  you-can-add: "127.0.0.2"
  as-much-player-as-you-want: "172.0.0.1"


# Discord Integration support

integrations:
  discord:
    enabled: true
    # Method: "webhook" or "bot"
    method: "bot"
    bot-token: "insert-your-bot-token-here"
    webhook-url: "https://discord.com/api/webhooks/0123456789123456789/webhook-token"
    # This setting required only if you are using Discord bot instead of Webhook. Remember, this is Channel ID, not the Channel name.
    # For more information about getting Channel ID, refer to https://support.discord.com/hc/en-us/articles/206346498
    alert-channel-id: "0123456789123456789"

# Hide the plugin
plugin:
  hide: true
  message-unknown-command: 'Unknown command. Type "/help" for help.'

# Messages to announce to integrations, placeholder and color code supported
messages:
  logging:
    unknown-admin: "{time} {player} have matched administrator permissions but not have whitelisted!"
    invalid-address: "{time} {player} have different IP address with whitelisted! Currently whitelisted address: %old_address%"
    success-whitelisted-ip: "{time} {player} have been whitelisted with IP address %ip_address%"
    success-removed-admin: "{time} {player} have been removed from administrator list"
  console:
    configuration-reloaded: 'Configuration reloaded!'
    invalid-command: 'Invalid command argument!'
    unknown-admin: "{time} {player} have matched administrator permissions but not have whitelisted!"
    invalid-address: "{time} {player} have different IP address with whitelisted! Currently whitelisted address: %old_address%"
    success-whitelisted-ip: "{time} {player} have been whitelisted with IP address %ip_address%"
    success-removed-admin: "{time} {player} have been removed from administrator list"
  integration:
    unknown-admin: "{time} {player} have matched administrator permissions but not have whitelisted!"
    invalid-address: "{time} {player} have different IP address with whitelisted! Currently whitelisted address: %old_address%"
    success-whitelisted-ip: "{time} {player} have been whitelisted with IP address %ip_address%"
    success-removed-admin: "{time} {player} have been removed from administrator list"
  kick:
    unknown-admin: "You have matched administrator permissions but not have whitelisted!"
    invalid-address: "You have different IP address with whitelisted!"